### PR TITLE
import json as simplejson

### PR DESCRIPTION
**Pull request by SafwatHalaby**
I had an error until I changed this line, not sure if it's the right thing to do.
The error was

```
Traceback (most recent call last):
  File "./run", line 22, in <module>
    aarddict.main()
  File "/home/cyber/documents/programming/git/desktop/aarddict/__init__.py", line 93, in main
    import aarddict.qtui
  File "/home/cyber/documents/programming/git/desktop/aarddict/qtui.py", line 47, in <module>
    from aarddict.dictionary import (format_title,
  File "/home/cyber/documents/programming/git/desktop/aarddict/dictionary.py", line 29, in <module>
    import simplejson
ImportError: No module named simplejson

```

### CODE REVIEW

**Comment by itkach** [comment]
The right thing to do is to install simplejson, as specified in install_requires in setup.py. Are you not using setup.py?

**Comment by itkach** [comment]
Also, if I may suggest, consider using http://aarddict.org/2/ instead. Version for desktop is web-based and not very fancy, but does the job and the dictionaries are quite a bit smaller.

**Comment by SafwatHalaby** [comment]
Installing simplejson did not resolve this, however that change did.
See this:
http://stackoverflow.com/questions/2604841/importerror-no-module-named-simplejson

**Comment by itkach** [comment]
If "installing simplejson" did not resolve this then you did not install simplejson. No, really. What exactly did you do to install  simplejson and aarddict?

**Comment by SafwatHalaby** [comment]
It is very likely that I did not do it properly. It's my first time playing around with Python.
I don't really care though, I managed to get Aardict working.

Thanks for your time :)

**Comment by SafwatHalaby** [comment]
Is installing SImplejson better than the change I did in any way?

**Comment by itkach** [comment]
> Is installing SImplejson better than the change I did in any way?

It is generally more practical to set up environment to meet program expectations (which is a fairly well known set of widely applicable practices that are the same or very similar for many/most applications) than to modify programs (which is pretty much always unique and special). Some programs can't be modified because you only have binary. Some programs are hard to modify because they are complex and/or are written in an obscure way. Changes have consequence. Even this, seemingly innocuous change, has consequences. The application can no longer work under Python 2.5. Also, JSON operations are now 100-200x slower on Python 2.6, because json module in Python 2.6 doesn't come with C extension. Also, it probably broke the app under PyPy, because json module in some recent versions of PyPy returns unicode where simplejson would have returned bytes (perhaps it's a bug). Perhaps none of this matters to you, but hopefully this illustrates my point. And this is just for a fairly simple library that has an equivalent in Python standard library. I'd be curious to see how you try to replace PyICU/ICU or PyQt/Qt4 if they were not already installed on your system (apparently by some lucky accident).

**Comment by SafwatHalaby** [comment]
I see, thanks for elaborating. I think I will try fixing it properly.

**Pull request closed without merging**
